name: Install Drupal
description: Install Drupal using DDEV to test config

inputs:
  aws-role:
    description: The arn of the aws role to use with ecr.
    required: true
  aws-region:
    description: The aws region to use with ecr.
    required: false
    default: us-east-1
  ssh-key:
    description: The ssh key for composer authentication.
    required: true
  composer-auth:
    description: Json formatted composer auth data.
    required: true

runs: 
  using: composite
  steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.aws-region }}

        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Setup Composer credentials
      shell: bash
      run: |
        mkdir -p .ddev/homeadditions/.ssh
        echo "${{ inputs.ssh-key }}" > .ddev/homeadditions/.ssh/id_rsa
        chmod 700 .ddev/homeadditions/.ssh
        chmod 600 .ddev/homeadditions/.ssh/id_rsa
        mkdir -p .ddev/homeadditions/.composer
        echo '${{ inputs.composer-auth }}' > .ddev/homeadditions/.composer/auth.json

    - name: Setup DDEV
      uses: ddev/github-action-setup-ddev@v1

    - name: Install unupdated site
      shell: bash
      run: |
        ddev composer install
        ddev install-site
