name: Install Drupal
description: Install Drupal using DDEV to test config

inputs:
  ECR_PUSH_ROLE:
    description: 'The role to assume to push to ECR'
    required: true
  ECR_AWS_REGION:
    description: 'The AWS region for ECR'
    required: true
  COMPOSER_SSH_KEY:
    description: 'The SSH key for Composer'
    required: true
  COMPOSER_AUTH:
    description: 'The Composer auth.json file'
    required: true
    
runs: 
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.ECR_PUSH_ROLE }}
        aws-region: ${{ inputs.ECR_AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Configure git
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "
    
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Composer credentials
      shell: bash
      run: |
        mkdir -p .ddev/homeadditions/.ssh
        echo "${{ inputs.COMPOSER_SSH_KEY }}" > .ddev/homeadditions/.ssh/id_rsa
        chmod 700 .ddev/homeadditions/.ssh
        chmod 600 .ddev/homeadditions/.ssh/id_rsa
        mkdir -p .ddev/homeadditions/.composer
        echo '${{ inputs.COMPOSER_AUTH }}' > .ddev/homeadditions/.composer/auth.json

    - name: Setup DDEV
      uses: ddev/github-action-setup-ddev@v1

    - name: Install unupdated site
      shell: bash
      run: |
        ddev composer install
        ddev install-site